controllers:
    resource: ../src/Controller/
    type: attribute

planning_type:
    path: /planning_type/employe/{id}
    controller: App\Controller\PlanningTypeController::showEmployePlanning
    methods: [GET]

detail_planning:
    path: /api/plannings/{id}
    controller: App\Controller\PlanningController::getDetailPlanning
    methods: [GET]
